---
title: Wild Life Bakery
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@wildlifebakery.com
description: 90 Albert St East Brunswick. Beautiful sourdough bread and pastries,
  breakfast and  lunch, 7:30am – 3pm Tuesday–Sunday.
baseurl: ''
url: ''
twitter_username: wildlifebakery
instagram_username: wildlifebakery
facebook_username: wildlifebakery
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
